<?php
// @@protoc_insertion_point(namespace:.Person)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: cbstest.proto
 *
 * -*- magic methods -*-
 *
 * @method string getName()
 * @method void setName(\string $value)
 * @method string getId()
 * @method void setId(\string $value)
 * @method string getEmail()
 * @method void setEmail(\string $value)
 * @method string getMoney()
 * @method void setMoney(\string $value)
 */
class Person extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.Person)
  
  /**
   * @var string $name
   * @tag 1
   * @label required
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $name;
  
  /**
   * @var string $id
   * @tag 2
   * @label required
   * @type \ProtocolBuffers::TYPE_INT32
   **/
  protected $id;
  
  /**
   * @var string $email
   * @tag 3
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $email;
  
  /**
   * @var string $money
   * @tag 4
   * @label optional
   * @type \ProtocolBuffers::TYPE_DOUBLE
   **/
  protected $money;
  
  
  // @@protoc_insertion_point(properties_scope:.Person)

  // @@protoc_insertion_point(class_scope:.Person)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "name",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT32,
        "name"     => "id",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "email",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(4, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_DOUBLE,
        "name"     => "money",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      // @@protoc_insertion_point(builder_scope:.Person)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
